01_explore_dataset.ipynb

Purpose:

Understand MOS data
Check duplicates
Verify matching files
Basic dataset statistics

In [74]:
import sqlite3
import pandas as pd

DB_PATH = "../data/processed/system_data.db"

conn = sqlite3.connect(DB_PATH)

MOS Dataset

In [75]:
mos_df = pd.read_sql(
    "SELECT * FROM load_raw_mos",
    conn
)

mos_df.head()

   index                     file    MOS
0      0  sys64e2f-utt491a78a.wav  4.000
1      1  sys64e2f-utt8485f83.wav  3.625
2      2  sys7ab3c-utt1417b69.wav  3.375
3      3  sys7ab3c-uttb548b8d.wav  2.000
4      4  sys2e1cb-uttbab062c.wav  3.375

Check Duplicate Files

In [76]:
duplicates = pd.read_sql("""
SELECT
    file,
    COUNT(*) AS cnt
FROM load_raw_mos
GROUP BY file
HAVING COUNT(*) > 1
""", conn)

duplicates

Empty DataFrame
Columns: [file, cnt]
Index: []

In [77]:
print("Duplicate files:", len(duplicates))

Duplicate files: 0

Audio Feature Dataset

In [78]:
feature_df = pd.read_sql(
    "SELECT * FROM wav_attribute",
    conn
)

feature_df.head()

,file,duration,spectral_rolloff,spectral_contrast,silence_ratio,pitch_mean,pitch_std,pitch_min,pitch_max,pitch_range,energy_mean,energy_std,energy_range,spectral_centroid,spectral_bandwidth,zcr
0,sysc382e-uttcbd8617.wav,4.935000,3686.743952,17.951794,0.157042,262.214969,91.436661,54.566628,352.187805,297.621176,0.038453,0.027381,0.143108,2082.327697,1566.831201,0.143882
1,sys05205-utta21631b.wav,2.610063,3374.047256,19.893332,0.178564,253.239859,91.752260,50.229029,400.909091,350.680062,0.038927,0.026585,0.099773,1901.424400,1475.499787,0.165307
2,sys9e6de-utt9543789.wav,3.825375,2448.502604,19.831247,0.222037,262.346567,99.408117,50.000000,385.133195,335.133195,0.037775,0.028923,0.126565,1274.863814,1400.967827,0.078316
3,syseba96-utt04ec954.wav,2.282688,3765.082465,22.258781,0.242998,221.760204,80.087602,50.000000,377.727806,327.727806,0.037197,0.028310,0.110955,2196.692779,1759.131452,0.194756
4,sys94e9f-utt0c88a0a.wav,4.991437,4152.093349,19.284805,0.416601,225.209878,92.166091,53.964831,400.909091,346.944260,0.028692,0.030125,0.115645,2124.335687,1804.210904,0.153787

Matching Files

In [ ]:
match_count = pd.read_sql("""
SELECT COUNT(*) AS total
FROM wav_attribute w
INNER JOIN load_raw_mos m
ON w.file = m.file
""", conn)

match_count

Database Table Info

In [79]:
pd.read_sql(
    "PRAGMA table_info(wav_attribute)",
    conn
)

    cid                name  type  notnull dflt_value  pk
0     0                file  TEXT        0       None   0
1     1            duration  REAL        0       None   0
2     2    spectral_rolloff  REAL        0       None   0
3     3   spectral_contrast  REAL        0       None   0
4     4       silence_ratio  REAL        0       None   0
5     5          pitch_mean  REAL        0       None   0
6     6           pitch_std  REAL        0       None   0
7     7           pitch_min  REAL        0       None   0
8     8           pitch_max  REAL        0       None   0
9     9         pitch_range  REAL        0       None   0
10   10         energy_mean  REAL        0       None   0
11   11          energy_std  REAL        0       None   0
12   12        energy_range  REAL        0       None   0
13   13   spectral_centroid  REAL        0       None   0
14   14  spectral_bandwidth  REAL        0       None   0
15   15                 zcr  REAL        0       None   0